config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
      params.require(:restaurant).permit(
        :id,
        :name,
        :address,
        :phone_number,
        :category
      )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  private

  def review_params
      params.require(:review).permit(
        :id,
        :content,
        :rating
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/restaurants">All restaurants</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/restaurants/new">Create a restaurant</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Category</th>
      <th scope="col">More info</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
    <tr>
      <th scope="row"><%= restaurant.id %></th>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.phone_number %></td>
      <td><%= restaurant.category %></td>
      <td><%= link_to "Show more", restaurant_path(restaurant)%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<!-- <form>
  <div class="mb-3">
    <label for="disabledTextInput" class="form-label">Name</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="Put the restaurant's name here">
  </div>
  <div class="mb-3">
    <label for="disabledTextInput" class="form-label">Address</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="Put the restaurant's address here">
  </div>
  <div class="mb-3">
    <label for="disabledTextInput" class="form-label">Phone Number</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="Put the restaurant's phone number here">
  </div>
  <div class="mb-3">
      <label for="disabledSelect" class="form-label">Category Options</label>
      <select id="disabledSelect" class="form-select" placeholder="Choose from options">
        <option>Chinese</option>
        <option>Italian</option>
        <option>Japanese</option>
        <option>French</option>
        <option>Belgian</option>
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form> -->

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, as: :select, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<p><%= link_to "Add a review", new_restaurant_review_path(@restaurant)%></p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Content</th>
      <th scope="col">Rate</th>
    </tr>
  </thead>
  <tbody>
    <% Review.select { |element| element.restaurant_id == @restaurant.id }.each do |review| %>
    <tr>
      <td><%= review.id %></td>
      <td><%= review.content %></td>
      <td><%= review.rating %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>